package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"

	"github.com/Arismonx/Golang-GraphQl/graph/handlers"
	"github.com/Arismonx/Golang-GraphQl/graph/model"
)

// GetPlayers is the resolver for the getPlayers field.
func (r *queryResolver) GetPlayers(ctx context.Context) ([]*model.Player, error) {
	return handlers.GetPlayers(), nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
